services:
  backend:
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: >
      ./gradlew bootRun --no-daemon -Dspring-boot.run.profiles=dev -Dspring.devtools.restart.enabled=true -Dspring.devtools.livereload.enable=true
    ports:
      - "8080:8080"
    container_name: marketplace-backend
    volumes:
      - ./api:/app:rw,cached
      - gradle-cache-backend:/home/gradle/.gradle:rw
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    environment:
      VITE_BACKEND_URL: http://localhost:8080
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
    container_name: marketplace-frontend
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - type: bind
        source: ./client
        target: /app
      - type: volume
        target: /app/node_modules

  backend-tests:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: marketplace-backend-tests
    command: >
     ./gradlew clean test --refresh-dependencies --no-daemon
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./api:/app:cached
      - gradle-cache-tests:/home/gradle/.gradle:rw

  db:
    image: postgres:15
    container_name: marketplace-database
    ports:
      - "15433:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  gradle-cache-backend:
  gradle-cache-tests:
  postgres_data:

networks:
  app-network:
    driver: bridge
