services:
  backend:
    build:
      context: ./marketplace-backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_SECRET_CLIENT: ${GOOGLE_SECRET_CLIENT}
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
      FACEBOOK_SECRET_CLIENT: ${FACEBOOK_SECRET_CLIENT}
      UNSPLASH_API_KEY: ${UNSPLASH_API_KEY}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      STORAGE_REGION: ${STORAGE_REGION}
      STORAGE_ENDPOINT: ${STORAGE_ENDPOINT}
      STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      STORAGE_SECRET_KEY: ${STORAGE_SECRET_KEY}
      STORAGE_BUCKET_NAME: ${STORAGE_BUCKET_NAME}
    volumes:
      - ./marketplace-backend:/app:rw,cached,rshared
      - type: bind
        source: ./marketplace-backend/mvnw
        target: /app/mvnw
        read_only: false
      - ~/.m2:/root/.m2:cached
    depends_on:
      - db
      - rabbitmq
      - minio
    networks:
      - app-network

  frontend:
    environment:
      VITE_BACKEND_URL: http://localhost:8080
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
    container_name: marketplace-frontend
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - type: bind
        source: ./client
        target: /app
      - type: volume
        target: /app/node_modules

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Port AMQP
      - "15672:15672"  # Port interface de gestion
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    networks:
      - app-network
    environment:
      MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_KEY}
    command: server /data --console-address ":9001"

  db:
    image: postgres:15
    container_name: marketplace-database
    ports:
      - "15433:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  maven-repo:
  maven-repo-tests:
  postgres_data:
  rabbitmq_data:
  minio_storage:

networks:
  app-network:
    driver: bridge
